# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""initialize database

Revision ID: 0e958e632a9d
Revises:
Create Date: 2026-03-16 10:04:48.125706

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e958e632a9d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "a2a_request_contexts",
        sa.Column("context_id", sa.String(length=256), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("context_id"),
    )
    op.create_table(
        "a2a_request_tasks",
        sa.Column("task_id", sa.String(length=256), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("trace_id", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "model_providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("base_url", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("watsonx_project_id", sa.String(length=256), nullable=True),
        sa.Column("watsonx_space_id", sa.String(length=256), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("registry", sa.String(length=2048), nullable=True),
        sa.Column("state", sa.Enum("online", "offline", name="modelproviderstate"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("base_url"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "configurations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("configuration_type", sa.Enum("system", "user", name="configurationtype"), nullable=False),
        sa.Column("default_llm_model", sa.String(length=256), nullable=True),
        sa.Column("default_embedding_model", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_unique_system_configuration",
        "configurations",
        ["configuration_type"],
        unique=True,
        postgresql_where="configuration_type = 'system'",
    )
    op.create_table(
        "connectors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("created", "auth_required", "connected", "disconnected", name="connectorstate"),
            nullable=True,
        ),
        sa.Column("auth", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("auth_state", sa.String(length=256), nullable=True),
        sa.Column("disconnect_reason", sa.String(), nullable=True),
        sa.Column("disconnect_permanent", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", "created_by", name="uk_url"),
    )
    op.create_index(op.f("ix_connectors_auth_state"), "connectors", ["auth_state"], unique=True)
    op.create_table(
        "providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=2048), nullable=False),
        sa.Column("source_type", sa.String(length=32), server_default="api", nullable=False),
        sa.Column("origin", sa.String(length=2048), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("agent_card", sa.JSON(), nullable=False),
        sa.Column("state", sa.Enum("online", "offline", name="providerstate"), server_default="online", nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source"),
    )
    op.create_table(
        "contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("trace_id", sa.String(length=256), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("comment_tags", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.CheckConstraint("rating IN (1, -1)", name="rating_check"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "parent_entity", sa.Enum("provider", "model_provider", "user", name="envstoreentity"), nullable=False
        ),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("model_provider_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "(parent_entity = 'provider' AND provider_id IS NOT NULL) OR (parent_entity = 'model_provider' AND model_provider_id IS NOT NULL) OR(parent_entity = 'user' AND user_id IS NOT NULL)",
            name="parent_entity_matches_reference",
        ),
        sa.CheckConstraint(
            "(provider_id IS NOT NULL)::int + (model_provider_id IS NOT NULL)::int + (user_id IS NOT NULL)::int= 1",
            name="exactly_one_reference",
        ),
        sa.ForeignKeyConstraint(["model_provider_id"], ["model_providers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "parent_entity", "model_provider_id", name="uk_model_provider"),
        sa.UniqueConstraint("key", "parent_entity", "provider_id", name="uk_provider"),
        sa.UniqueConstraint("key", "parent_entity", "user_id", name="uk_user"),
    )
    op.create_index("idx_entity_attributes_model_provider", "variables", ["model_provider_id"], unique=False)
    op.create_index("idx_entity_attributes_provider", "variables", ["provider_id"], unique=False)
    op.create_index("idx_entity_attributes_user", "variables", ["user_id"], unique=False)
    op.create_table(
        "context_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_context_history_context_id", "context_history", ["context_id"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("content_type", sa.String(length=256), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("file_type", sa.Enum("user_upload", "extracted_text", name="file_type"), nullable=False),
        sa.Column("parent_file_id", sa.UUID(), nullable=True),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vector_stores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("model_id", sa.String(length=256), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["context_id"], ["contexts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "text_extractions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "in_progress", "completed", "failed", "cancelled", name="extraction_status"),
            nullable=False,
        ),
        sa.Column("job_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("extraction_metadata", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id"),
    )
    op.create_table(
        "vector_store_documents",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("vector_store_id", sa.UUID(), nullable=False),
        sa.Column("usage_bytes", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vector_store_id"], ["vector_stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "vector_store_id", name="vector_store_documents_pk"),
    )
    op.create_table(
        "extraction_files",
        sa.Column("extraction_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["extraction_id"], ["text_extractions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("extraction_id", "format", name="uq_extraction_files_extraction_id_format"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("extraction_files")
    op.drop_table("vector_store_documents")
    op.drop_table("text_extractions")
    op.drop_table("vector_stores")
    op.drop_table("files")
    op.drop_index("idx_context_history_context_id", table_name="context_history")
    op.drop_table("context_history")
    op.drop_index("idx_entity_attributes_user", table_name="variables")
    op.drop_index("idx_entity_attributes_provider", table_name="variables")
    op.drop_index("idx_entity_attributes_model_provider", table_name="variables")
    op.drop_table("variables")
    op.drop_table("user_feedback")
    op.drop_table("contexts")
    op.drop_table("providers")
    op.drop_index(op.f("ix_connectors_auth_state"), table_name="connectors")
    op.drop_table("connectors")
    op.drop_index(
        "ix_unique_system_configuration", table_name="configurations", postgresql_where="configuration_type = 'system'"
    )
    op.drop_table("configurations")
    op.drop_table("users")
    op.drop_table("model_providers")
    op.drop_table("a2a_request_tasks")
    op.drop_table("a2a_request_contexts")
    # ### end Alembic commands ###
