# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""Remove managed provider features, add kagenti sync support

Revision ID: c0095389475b
Revises: 764ca0fd6a5b
Create Date: 2026-03-09 13:33:33.334880

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c0095389475b"
down_revision: str | None = "764ca0fd6a5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop removed tables
    op.drop_table("provider_builds")
    op.drop_table("provider_discoveries")

    # Create new providerstate enum (same values as unmanagedstate)
    providerstate = postgresql.ENUM("online", "offline", name="providerstate", create_type=False)
    providerstate.create(op.get_bind(), checkfirst=True)

    # Add new columns
    op.add_column("providers", sa.Column("source_type", sa.String(length=32), server_default="api", nullable=False))
    op.add_column("providers", sa.Column("state", providerstate, nullable=True))

    # Migrate unmanaged_state data to new state column, default to 'online'
    op.execute("UPDATE providers SET state = COALESCE(unmanaged_state::text::providerstate, 'online')")

    # Make state non-nullable now that all rows have a value
    op.alter_column("providers", "state", nullable=False, server_default="online")

    # Drop old columns
    op.drop_column("providers", "auto_stop_timeout_sec")
    op.drop_column("providers", "version_info")
    op.drop_column("providers", "unmanaged_state")
    op.drop_column("providers", "registry")
    op.drop_column("providers", "type")

    # Drop old enum types
    sa.Enum(name="unmanagedstate").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="providertype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="buildstate").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="discoverystate").drop(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers",
        sa.Column(
            "type", postgresql.ENUM("managed", "unmanaged", name="providertype"), autoincrement=False, nullable=False
        ),
    )
    op.add_column("providers", sa.Column("registry", sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.add_column(
        "providers",
        sa.Column(
            "unmanaged_state",
            postgresql.ENUM("online", "offline", name="unmanagedstate"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "providers",
        sa.Column(
            "version_info",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text('\'{"docker": null, "github": null}\'::json'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("providers", sa.Column("auto_stop_timeout_sec", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("providers", "state")
    op.drop_column("providers", "source_type")
    op.create_table(
        "provider_discoveries",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("docker_image", sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("agent_card", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "in_progress", "completed", "failed", name="discoverystate"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("provider_discoveries_created_by_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("provider_discoveries_pkey")),
    )
    op.create_table(
        "provider_builds",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("source", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("missing", "in_progress", "completed", "failed", "build_completed", name="buildstate"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("destination", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column(
            "on_complete",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text('\'{"type": "no_action"}\'::json'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("build_configuration", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("provider_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("provider_builds_created_by_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.id"], name=op.f("provider_builds_provider_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("provider_builds_pkey")),
    )
    # ### end Alembic commands ###
