[tools]
# runtime
"lima" = "2.0.3"
packer = "latest"

# Python
uv = "latest"

# Node.js
nodejs = "24"
pnpm = "10"

# Kubernetes
helm = "latest"
kubeconform = "latest"

# misc
yq = "latest"
"pipx:toml-cli" = "latest"
fd = "latest"
"github:google/addlicense" = "latest"
gum = "latest"
hadolint = "latest"
lychee = "latest"
telepresence = "latest"

[settings]
experimental = true # for python.uv_venv_auto
python.uv_venv_auto = true
task.disable_spec_from_run_scripts = true # opt-in to new task behavior
raw = true

[hooks]
postinstall = ["{{ mise_bin }} setup"]

[env]
UV_PYTHON_PREFERENCE = "only-managed"

[task_config]
includes = [
    "./tasks.toml",
    "helm/tasks.toml",
    "apps/adk-cli/tasks.toml",
    "apps/adk-py/tasks.toml",
    "apps/adk-server/tasks.toml",
    "apps/adk-ui/tasks.toml",
    "apps/adk-ts/tasks.toml",
    "apps/microshift-vm/tasks.toml",
    "agents/tasks.toml",
    "docs/tasks.toml",
    "apps/docs-site/tasks.toml",
]
