{{- if .Values.gateway.enabled }}
{{- $uiHost := index (splitList ":" (urlParse .Values.auth.nextauthUrl).host) 0 }}
{{- $apiHost := index (splitList ":" (urlParse .Values.auth.apiUrl).host) 0 }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentstack.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentRef.name }}
      namespace: {{ .Values.gateway.parentRef.namespace }}
  hostnames:
    - {{ $uiHost | quote }}
  rules:
    - backendRefs:
        - name: adk-ui-svc
          port: {{ .Values.ui.service.port }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentstack.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentRef.name }}
      namespace: {{ .Values.gateway.parentRef.namespace }}
  hostnames:
    - {{ $apiHost | quote }}
  rules:
    - backendRefs:
        - name: adk-server-svc
          port: {{ .Values.server.service.port }}
{{- end }}
