{{- $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: agentstack-providers-secret
type: Opaque
stringData:
  model_providers_registry.yaml: |
    {{- if .Values.modelProviders }}
    providers:
      {{- range $idx, $p := $root.Values.modelProviders }}
      - {{ $p | toYaml | nindent 8 | trim }}
      {{- end }}
    {{- else }}
    providers: [ ]
    {{- end }}
