# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate Python SDK reference docs (MDX) from exports_structure.json.

Uses Jinja2 templates from the docs_templates/ directory.
Run `uv run python introspect_exports.py` first to produce exports_structure.json.

Usage:  uv run python generate_docs.py
"""

from __future__ import annotations

import argparse
import json
from collections import OrderedDict
from functools import partial
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

# ---------------------------------------------------------------------------
# Paths  (module-level defaults; all can be overridden via CLI flags)
# ---------------------------------------------------------------------------

AUTOGEN_WARNING = """\
{/*

⚠️⚠️⚠️ WARNING ⚠️⚠️⚠️

DO NOT EDIT THIS FILE BY HAND, IT IS AUTOMATICALLY GENERATED BY `mise agentstack-sdk-py:docs`

*/}"""

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------

# The five top-level modules shown on the overview page.
TOP_MODULES = [
    {
        "title": "Server",
        "description": "Core server for creating and running A2A-compatible agents",
        "filename": "server",
    },
    {
        "title": "A2A",
        "description": "Extensions for authentication, services, tools, UI, and interactions",
        "filename": "a2a",
    },
    {
        "title": "Platform API",
        "description": "Clients for files, vector stores, contexts, providers, and more",
        "filename": "platform",
    },
    {
        "title": "Types",
        "description": "Core type definitions and base classes",
        "filename": "types",
    },
    {
        "title": "Utilities",
        "description": "Utility helpers",
        "filename": "util",
    },
]

# Each entry drives a single .mdx page.
#
# json_key        – key in exports_structure.json to pull items from; None = index-only page
# filename        – output filename (no .mdx extension)
# title           – MDX frontmatter title
# description     – MDX frontmatter description
# import_path     – Python import path shown in the code snippet
# submodule_cards – optional list of child modules rendered as a card grid
# group_by_origin – split items into sections per origin sub-module (used for platform)
PAGE_CONFIG: list[dict] = [
    # ── server ────────────────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.server",
        "filename": "server",
        "title": "Server",
        "description": "Core server for creating and running A2A-compatible agents",
        "import_path": "agentstack_sdk.server",
    },
    # ── a2a (index, items live in sub-pages) ──────────────────────────────────
    {
        "json_key": None,
        "filename": "a2a",
        "title": "A2A Extensions",
        "description": "Extensions for the A2A protocol — authentication, services, tools, UI, and interactions",
        "import_path": "agentstack_sdk.a2a.extensions",
        "submodule_cards": [
            {"title": "Auth", "filename": "a2a-auth", "description": "OAuth and secrets authentication"},
            {"title": "Common", "filename": "a2a-common", "description": "Shared base classes and form types"},
            {"title": "Interactions", "filename": "a2a-interactions", "description": "Human-in-the-loop interaction extensions"},
            {"title": "Services", "filename": "a2a-services", "description": "LLM, embedding, MCP, and platform services"},
            {"title": "Tools", "filename": "a2a-tools", "description": "Tool call approval extensions"},
            {"title": "UI", "filename": "a2a-ui", "description": "Rich UI component extensions"},
        ],
    },
    # ── a2a.auth (index) ──────────────────────────────────────────────────────
    {
        "json_key": None,
        "filename": "a2a-auth",
        "title": "Auth Extensions",
        "description": "OAuth and secrets authentication extensions",
        "import_path": "agentstack_sdk.a2a.extensions.auth",
        "submodule_cards": [
            {"title": "OAuth", "filename": "a2a-auth-oauth", "description": "OAuth 2.0 flow extensions"},
            {"title": "Secrets", "filename": "a2a-auth-secrets", "description": "Secrets injection extensions"},
        ],
    },
    # ── a2a.auth.oauth ────────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.a2a.extensions.auth.oauth",
        "filename": "a2a-auth-oauth",
        "title": "OAuth Extensions",
        "description": "OAuth 2.0 flow extensions",
        "import_path": "agentstack_sdk.a2a.extensions.auth.oauth",
        "submodule_cards": [
            {
                "title": "OAuth Storage",
                "filename": "a2a-auth-oauth-storage",
                "description": "Storage backends for OAuth flow state",
            }
        ],
    },
    # ── a2a.auth.oauth.storage ────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.a2a.extensions.auth.oauth.storage",
        "filename": "a2a-auth-oauth-storage",
        "title": "OAuth Storage",
        "description": "Storage backends for OAuth flow state",
        "import_path": "agentstack_sdk.a2a.extensions.auth.oauth.storage",
    },
    # ── a2a.auth.secrets ──────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.a2a.extensions.auth.secrets",
        "filename": "a2a-auth-secrets",
        "title": "Secrets Extensions",
        "description": "Secrets injection extensions",
        "import_path": "agentstack_sdk.a2a.extensions.auth.secrets",
    },
    # ── a2a.common ────────────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.a2a.extensions.common",
        "filename": "a2a-common",
        "title": "Common Types",
        "description": "Shared base classes and form types for extensions",
        "import_path": "agentstack_sdk.a2a.extensions.common",
    },
    # ── a2a.interactions ──────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.a2a.extensions.interactions",
        "filename": "a2a-interactions",
        "title": "Interaction Extensions",
        "description": "Human-in-the-loop interaction extensions",
        "import_path": "agentstack_sdk.a2a.extensions.interactions",
    },
    # ── a2a.services ──────────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.a2a.extensions.services",
        "filename": "a2a-services",
        "title": "Service Extensions",
        "description": "LLM, embedding, MCP, and platform service extensions",
        "import_path": "agentstack_sdk.a2a.extensions.services",
    },
    # ── a2a.tools ─────────────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.a2a.extensions.tools",
        "filename": "a2a-tools",
        "title": "Tool Extensions",
        "description": "Tool call approval extensions",
        "import_path": "agentstack_sdk.a2a.extensions.tools",
    },
    # ── a2a.ui ────────────────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.a2a.extensions.ui",
        "filename": "a2a-ui",
        "title": "UI Extensions",
        "description": "Rich UI component extensions",
        "import_path": "agentstack_sdk.a2a.extensions.ui",
    },
    # ── platform (grouped by sub-module) ──────────────────────────────────────
    {
        "json_key": "agentstack_sdk.platform",
        "filename": "platform",
        "title": "Platform API",
        "description": "Clients for files, vector stores, contexts, providers, and more",
        "import_path": "agentstack_sdk.platform",
        "group_by_origin": True,
    },
    # ── types ─────────────────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.types",
        "filename": "types",
        "title": "SDK Types",
        "description": "Core type definitions and base classes",
        "import_path": "agentstack_sdk.types",
    },
    # ── util ──────────────────────────────────────────────────────────────────
    {
        "json_key": "agentstack_sdk.util",
        "filename": "util",
        "title": "Utilities",
        "description": "Utility helpers",
        "import_path": "agentstack_sdk.util",
    },
]

# ---------------------------------------------------------------------------
# Jinja2 custom filters
# ---------------------------------------------------------------------------

_TYPE_PREFIXES = (
    "agentstack_sdk.a2a.extensions.common.form.",
    "agentstack_sdk.a2a.extensions.auth.oauth.oauth.",
    "agentstack_sdk.a2a.extensions.auth.secrets.secrets.",
    "agentstack_sdk.a2a.extensions.",
    "agentstack_sdk.a2a.",
    "agentstack_sdk.server.",
    "agentstack_sdk.platform.",
    "agentstack_sdk.",
    "a2a.types.",
    "collections.abc.",
    "typing.",
    "typing_extensions.",
    "datetime.",
    "uuid.",
    "pydantic.",
    "starlette.",
    "httpx.",
    "ssl.",
    "os.",
    "contextlib.",
    "abc.",
)


def _shorten_type(s: str | None) -> str:
    if not s:
        return ""
    for prefix in _TYPE_PREFIXES:
        s = s.removeprefix(prefix)
    return s


def _first_line(text: str | None) -> str:
    if not text:
        return ""
    line = text.strip().split("\n")[0].strip().rstrip(".")
    return line.replace('"', "'")  # safe for MDX attribute strings


def _extra_lines(text: str | None) -> str:
    if not text:
        return ""
    lines = text.strip().split("\n")
    return "\n".join(lines[1:]).strip() if len(lines) > 1 else ""


def _sig_params(params: list[dict] | None, max_params: int | None = None) -> str:
    """Parameter names only — keeps accordion titles short."""
    if not params:
        return ""
    if max_params is not None:
        return ", ".join(p["name"] for p in params[:max_params]) + ("..." if len(params) > max_params else "")
    else:        
        return ", ".join(p["name"] for p in params)


def _truncate_val(val: str | None, max_len: int = 40) -> str:
    if not val:
        return ""
    return val[:max_len] + "..." if len(val) > max_len else val


def _table_type(s: str | None) -> str:
    """Shorten a type annotation and escape | so it doesn't break Markdown table columns."""
    result = _shorten_type(s)
    return result.replace("|", "\\|")


def _mdx_escape(text: str | None) -> str:
    """Escape characters that MDX/acorn would try to parse as JSX expressions."""
    if not text:
        return ""
    return text.replace("{", "\\{").replace("}", "\\}")


# ---------------------------------------------------------------------------
# Item helpers
# ---------------------------------------------------------------------------

_SKIP_KINDS = {"unknown"}

# ---------------------------------------------------------------------------
# Module → filename / import_path look-up (built lazily from PAGE_CONFIG)
# ---------------------------------------------------------------------------

_JSON_KEY_TO_FILENAME: dict[str, str] = {}
_JSON_KEY_TO_IMPORT_PATH: dict[str, str] = {}
_FILENAME_TO_TITLE: dict[str, str] = {}
_FILENAME_TO_PARENT: dict[str, str] = {}  # child filename → parent filename


def _ensure_module_maps() -> None:
    if _JSON_KEY_TO_FILENAME:
        return
    for cfg in PAGE_CONFIG:
        key = cfg.get("json_key")
        if key:
            _JSON_KEY_TO_FILENAME[key] = cfg["filename"]
            _JSON_KEY_TO_IMPORT_PATH[key] = cfg["import_path"]
        _FILENAME_TO_TITLE[cfg["filename"]] = cfg["title"]
        for card in cfg.get("submodule_cards", []):
            _FILENAME_TO_PARENT[card["filename"]] = cfg["filename"]


def _symbol_breadcrumb_ancestors(parent_filename: str) -> list[tuple[str, str]]:
    """Return ordered list of (title, filename) ancestors from root down to *parent_filename* (inclusive)."""
    _ensure_module_maps()
    chain: list[tuple[str, str]] = []
    current = parent_filename
    while current:
        title = _FILENAME_TO_TITLE.get(current, current.replace("-", " ").title())
        chain.append((title, current))
        current = _FILENAME_TO_PARENT.get(current, "")
    chain.reverse()
    return chain


def _find_longest_matching_json_key(origin: str) -> str | None:
    """Return the longest PAGE_CONFIG json_key that is a prefix of *origin*."""
    _ensure_module_maps()
    best_key: str | None = None
    best_len = 0
    for key in _JSON_KEY_TO_FILENAME:
        if (origin == key or origin.startswith(key + ".")) and len(key) > best_len:
            best_key = key
            best_len = len(key)
    return best_key


def _symbol_import_path(item: dict) -> str:
    """Best import path to use on a symbol's own page."""
    origin = item.get("origin", "")
    longest = _find_longest_matching_json_key(origin)
    if longest:
        return _JSON_KEY_TO_IMPORT_PATH[longest]
    # Fallback: use origin directly
    return origin


def _symbol_page_parent_filename(item: dict) -> str:
    """Filename of the parent module page for *item* (used as sub-directory)."""
    origin = item.get("origin", "")
    longest = _find_longest_matching_json_key(origin)
    if longest:
        return _JSON_KEY_TO_FILENAME[longest]
    # Fallback: slugify origin
    return origin.replace("agentstack_sdk.", "").replace(".", "-")


def _symbol_page_parent_title(parent_filename: str) -> str:
    """Human-readable title of the parent module page."""
    _ensure_module_maps()
    return _FILENAME_TO_TITLE.get(parent_filename, parent_filename.replace("-", " ").title())




# ---------------------------------------------------------------------------
# Item helpers
# ---------------------------------------------------------------------------


def _split_items(items: list[dict]) -> tuple[list[dict], list[dict], list[dict]]:
    classes = sorted([i for i in items if i.get("kind") == "class"], key=lambda i: i.get("name", ""))
    functions = sorted([i for i in items if i.get("kind") == "function"], key=lambda i: i.get("name", ""))
    constants = sorted([i for i in items if i.get("kind") not in ("class", "function")], key=lambda i: i.get("name", ""))
    return classes, functions, constants


def _origin_submodule(item: dict, base_key: str) -> str:
    origin = item.get("origin", "")
    prefix = base_key + "."
    if origin.startswith(prefix):
        return origin[len(prefix):].split(".")[0]
    return ""


def _import_example(import_path: str, classes: list[dict], functions: list[dict]) -> str:
    names = [i["name"] for i in (classes + functions)[:3]]
    if not names:
        return f"from {import_path} import ..."
    suffix = "  # ..." if len(classes) + len(functions) > 3 else ""
    return f"from {import_path} import {', '.join(names)}{suffix}"


def _build_group(title: str, import_path: str, items: list[dict]) -> dict:
    classes, functions, constants = _split_items(items)
    return {
        "title": title,
        "import_path": import_path,
        "import_example": _import_example(import_path, classes, functions),
        "classes": classes,
        "functions": functions,
        "constants": constants,
    }


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _make_env(templates_dir: Path) -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["first_line"] = _first_line
    env.filters["extra_lines"] = _extra_lines
    env.filters["shorten_type"] = _shorten_type
    env.filters["table_type"] = _table_type
    env.filters["mdx_escape"] = _mdx_escape
    env.filters["sig_params"] = _sig_params
    env.filters["sig_params_short"] = partial(_sig_params, max_params=4)
    env.filters["truncate_val"] = _truncate_val
    return env


def render_overview(env: Environment, version: str) -> str:
    tmpl = env.get_template("overview.mdx.j2")
    return tmpl.render(
        autogen_warning=AUTOGEN_WARNING,
        top_modules=TOP_MODULES,
        base_href=f"/{version}/reference/python-sdk",
    )


def render_page(env: Environment, cfg: dict, data: dict, version: str) -> str:
    json_key: str | None = cfg.get("json_key")
    import_path: str = cfg["import_path"]
    submodule_cards: list[dict] = cfg.get("submodule_cards", [])
    group_by_origin: bool = cfg.get("group_by_origin", False)
    base_href = f"/{version}/reference/python-sdk"
    symbol_base_href = f"{base_href}/{cfg['filename']}"

    items: list[dict] = []
    if json_key and json_key in data:
        items = [i for i in data[json_key] if i.get("kind") not in _SKIP_KINDS]

    groups: list[dict] = []
    if items:
        if group_by_origin:
            grouped: dict[str, list[dict]] = OrderedDict()
            for item in items:
                sub = _origin_submodule(item, json_key or "")
                grouped.setdefault(sub, []).append(item)
            for sub, sub_items in grouped.items():
                sub_title = sub.replace("_", " ").title() if sub else ""
                sub_import = f"{import_path}.{sub}" if sub else import_path
                groups.append(_build_group(sub_title, sub_import, sub_items))
        else:
            groups.append(_build_group("", import_path, items))

    all_classes = [c for g in groups for c in g["classes"]]
    all_functions = [f for g in groups for f in g["functions"]]
    import_example = _import_example(import_path, all_classes, all_functions) if items else ""

    tmpl = env.get_template("module.mdx.j2")
    return tmpl.render(
        autogen_warning=AUTOGEN_WARNING,
        title=cfg["title"],
        description=cfg["description"],
        import_path=import_path,
        import_example=import_example,
        submodule_cards=submodule_cards,
        groups=groups,
        base_href=base_href,
        symbol_base_href=symbol_base_href,
    )


# ---------------------------------------------------------------------------
# Symbol-level page renderers
# ---------------------------------------------------------------------------


def render_class_page(
    env: Environment,
    cls: dict,
    import_path: str,
    breadcrumb_ancestors: list[tuple[str, str]] | None = None,
    base_href: str = "",
) -> str:
    tmpl = env.get_template("class.mdx.j2")
    return tmpl.render(
        autogen_warning=AUTOGEN_WARNING,
        cls=cls,
        import_path=import_path,
        breadcrumb_ancestors=breadcrumb_ancestors or [],
        base_href=base_href,
    )


def render_function_page(
    env: Environment,
    fn: dict,
    import_path: str,
    breadcrumb_ancestors: list[tuple[str, str]] | None = None,
    base_href: str = "",
) -> str:
    tmpl = env.get_template("function.mdx.j2")
    return tmpl.render(
        autogen_warning=AUTOGEN_WARNING,
        fn=fn,
        import_path=import_path,
        breadcrumb_ancestors=breadcrumb_ancestors or [],
        base_href=base_href,
    )



# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Python SDK reference docs (MDX) from exports_structure.json.")
    parser.add_argument(
        "--json-file",
        type=Path,
        help="Path to the exports_structure.json manifest",
    )
    parser.add_argument(
        "--docs-dir",
        type=Path,
        help=f"Root docs output directory",
    )
    parser.add_argument(
        "--templates-dir",
        type=Path,
        help=f"Jinja2 templates directory",
    )
    args = parser.parse_args()

    json_file: Path = args.json_file
    docs_dir: Path = args.docs_dir
    templates_dir: Path = args.templates_dir

    if not json_file.exists():
        raise FileNotFoundError(
            f"exports_structure.json not found at {json_file}.\n"
            "Run `mise x -- uv run introspect_exports.py` first."
        )

    data = json.loads(json_file.read_text())
    env = _make_env(templates_dir)
    _ensure_module_maps()

    version = "development"
    out_dir = docs_dir / version / "reference" / "python-sdk"
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── overview + module pages (as before) ──────────────────────────────────
    content = render_overview(env, version)
    (out_dir / "overview.mdx").write_text(content)

    for cfg in PAGE_CONFIG:
        content = render_page(env, cfg, data, version)
        (out_dir / f"{cfg['filename']}.mdx").write_text(content)

    # ── auto-generated symbol pages ───────────────────────────────────────────
    # Collect all unique symbols across every module key in the JSON.
    # Dedup by (name, origin) so each real symbol gets exactly one page,
    # placed under the most specific matching PAGE_CONFIG module directory.
    generated_symbols: set[tuple[str, str]] = set()
    symbol_count = 0

    for json_key, items in data.items():
        for item in items:
            kind = item.get("kind")
            if kind in _SKIP_KINDS:
                continue
            name: str = item.get("name", "")
            origin: str = item.get("origin", json_key)
            if not name:
                continue

            dedup_key = (name, origin)
            if dedup_key in generated_symbols:
                continue
            generated_symbols.add(dedup_key)

            import_path = _symbol_import_path(item)
            parent_filename = _symbol_page_parent_filename(item)
            base_href = f"/{version}/reference/python-sdk"
            breadcrumb_ancestors = _symbol_breadcrumb_ancestors(parent_filename)

            symbol_dir = out_dir / parent_filename
            symbol_dir.mkdir(parents=True, exist_ok=True)

            if kind == "class":
                content = render_class_page(env, item, import_path, breadcrumb_ancestors, base_href)
            elif kind == "function":
                content = render_function_page(env, item, import_path, breadcrumb_ancestors, base_href)
            else:
                continue

            (symbol_dir / f"{name}.mdx").write_text(content)
            symbol_count += 1

    module_count = 1 + len(PAGE_CONFIG)
    print(
        f"\nGenerated {module_count} module pages + {symbol_count} symbol pages"
        f" in {version}/reference/python-sdk/"
    )


if __name__ == "__main__":
    main()
