# check

["adk-ts:check"]
depends = ["adk-ts:check:*"]

["adk-ts:check:prettier"]
run = "pnpm prettier --log-level silent --check src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx", "src/**/*.html", "src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/adk-ts"

["adk-ts:check:eslint"]
run = "pnpm eslint ."
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/adk-ts"

["adk-ts:check:tsc"]
run = "pnpm tsc --noEmit -p tsconfig.check.json"
sources = ["src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/adk-ts"

# fix

["adk-ts:fix"]
depends = ["adk-ts:fix:*"]

["adk-ts:fix:prettier"]
run = "pnpm prettier --log-level silent --write src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx", "src/**/*.html", "src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/adk-ts"

["adk-ts:fix:lint"]
run = "pnpm eslint . --fix"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/adk-ts"

# build

["adk-ts:build"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/adk-ts"
run = "pnpm build"
sources = ["src/**/*", "package.json", "tsconfig.json"]
outputs = { auto = true }
