apiVersion: v2
name: kagenti-adk
icon: https://raw.githubusercontent.com/kagenti/adk/main/docs/logo/beeai_framework_dark.svg
description: A Helm chart for Kubernetes
type: application
version: 0.8.2
appVersion: 0.8.2
dependencies:
  - condition: postgresql.enabled
    name: postgres
    alias: postgresql
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.18.x
  - condition: seaweedfs.enabled
    name: seaweedfs
    repository: https://seaweedfs.github.io/seaweedfs/helm
    version: 4.0.407
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.16.3
