# setup

["adk-cli:setup"]
extends = "python:setup"
depends = ["adk-py:setup"]
dir = "{{config_root}}/apps/adk-cli"

# check

["adk-cli:check"]
depends = ["adk-cli:check:*"]

["adk-cli:check:ruff-check"]
extends = "python:check:ruff"
depends = ["adk-cli:setup"]
dir = "{{config_root}}/apps/adk-cli"

["adk-cli:check:ruff-format"]
extends = "python:check:ruff-format"
depends = ["adk-cli:setup"]
dir = "{{config_root}}/apps/adk-cli"

["adk-cli:check:pyrefly"]
extends = "python:check:pyrefly"
dir = "{{config_root}}/apps/adk-cli"

# fix

["adk-cli:fix"]
depends = ["adk-cli:fix:*"]

["adk-cli:fix:ruff-check"]
extends = "python:fix:ruff"
depends = ["adk-cli:setup"]
dir = "{{config_root}}/apps/adk-cli"

["adk-cli:fix:ruff-format"]
extends = "python:fix:ruff-format"
depends = ["adk-cli:setup"]
dir = "{{config_root}}/apps/adk-cli"

# run

["adk-cli:run"]
description = "NOTE: Use double dash to pass extra args, like `mise adk-cli:run -- provider list`"
depends = ["adk-cli:setup", "adk-cli:build:copy-helm-chart"]
dir = "{{config_root}}/apps/adk-cli"
raw = true
run = "uv run kagenti-adk"

# build

["adk-cli:build:download-binaries"]
dir = "{{config_root}}/apps/adk-cli"
run = '''
set -e
LIMA_VERSION=$(yq -r '.tools["lima"]' ../../mise.toml)
mkdir -p ./vendor
echo '*' >./vendor/.gitignore
( test -f ./vendor/lima-$LIMA_VERSION/manylinux_2_34_x86_64/bin/limactl  || ( mkdir -p ./vendor/lima-$LIMA_VERSION/manylinux_2_34_x86_64  && curl -fsL -H "Authorization: Bearer $GITHUB_TOKEN" https://github.com/lima-vm/lima/releases/download/v${LIMA_VERSION}/lima-${LIMA_VERSION}-Linux-x86_64.tar.gz  | tar -xzf - -C ./vendor/lima-$LIMA_VERSION/manylinux_2_34_x86_64  )) &
( test -f ./vendor/lima-$LIMA_VERSION/manylinux_2_34_aarch64/bin/limactl || ( mkdir -p ./vendor/lima-$LIMA_VERSION/manylinux_2_34_aarch64 && curl -fsL -H "Authorization: Bearer $GITHUB_TOKEN" https://github.com/lima-vm/lima/releases/download/v${LIMA_VERSION}/lima-${LIMA_VERSION}-Linux-aarch64.tar.gz | tar -xzf - -C ./vendor/lima-$LIMA_VERSION/manylinux_2_34_aarch64 )) &
( test -f ./vendor/lima-$LIMA_VERSION/macosx_12_0_x86_64/bin/limactl     || ( mkdir -p ./vendor/lima-$LIMA_VERSION/macosx_12_0_x86_64     && curl -fsL -H "Authorization: Bearer $GITHUB_TOKEN" https://github.com/lima-vm/lima/releases/download/v${LIMA_VERSION}/lima-${LIMA_VERSION}-Darwin-x86_64.tar.gz | tar -xzf - -C ./vendor/lima-$LIMA_VERSION/macosx_12_0_x86_64     )) &
( test -f ./vendor/lima-$LIMA_VERSION/macosx_12_0_arm64/bin/limactl      || ( mkdir -p ./vendor/lima-$LIMA_VERSION/macosx_12_0_arm64      && curl -fsL -H "Authorization: Bearer $GITHUB_TOKEN" https://github.com/lima-vm/lima/releases/download/v${LIMA_VERSION}/lima-${LIMA_VERSION}-Darwin-arm64.tar.gz  | tar -xzf - -C ./vendor/lima-$LIMA_VERSION/macosx_12_0_arm64      )) &
wait
'''

["adk-cli:build:copy-helm-chart"]
depends = ["helm:build"]
dir = "{{config_root}}/apps/adk-cli"
run = "rm ./src/kagenti_cli/data/helm-chart.tgz 2>/dev/null || true && cp {{config_root}}/helm/dist/agentstack-*.tgz ./src/kagenti_cli/data/helm-chart.tgz"
sources = ["{{config_root}}/helm/dist/agentstack-*.tgz"]
outputs = ["./src/kagenti_cli/data/helm-chart.tgz"]

["adk-cli:build"]
depends = [
  "adk-cli:setup",
  "adk-cli:build:*",
  "adk-py:build",
]
dir = "{{config_root}}/apps/adk-cli"
sources = ["src/**/*", "hatch_build.py", "pyproject.toml", "vendor/lima/**/*"]
outputs = ["dist/**/*"]
run = '''
#!/usr/bin/env bash
set -euo pipefail

# Build sdist and wheel
rm -rf ./dist
uv build -q --out-dir ./dist
export lima_version=$(yq -r '.tools["lima"]' ../../mise.toml)
export version="$(yq -r '.project.version' pyproject.toml | tr -d -)"
export universal_wheel=$(realpath "./dist/kagenti_cli-$version-py3-none-any.whl")

# Pin versions from uv.lock in wheel
tmpdir="$(mktemp -d)"
unzip -q "$universal_wheel" -d "$tmpdir"
find "$tmpdir" -type f -exec chmod +r {} \;
insert_line=$(awk '/^Requires-Dist:/ {print FNR-1; exit}' "$tmpdir/kagenti_cli-${version}.dist-info/METADATA" | cut -d: -f1)
(
  head -n $insert_line "$tmpdir/kagenti_cli-${version}.dist-info/METADATA"
  uv export --no-editable --no-hashes --no-emit-workspace --no-dev --format requirements-txt | sed '/^[[:space:]]*#/d' | while IFS= read -r dep; do
    if [[ "$dep" =~ ^[a-zA-Z] ]]; then
      echo "Requires-Dist: $dep"
    else
      echo "Requires-Dist: $(yq -r '.project.name' "$dep/pyproject.toml")==$(yq -r '.project.version' "$dep/pyproject.toml" | tr -d '-')"
    fi
  done
  awk -v insert_line="$insert_line" 'NR > insert_line && $0 !~ /^Requires-Dist:/' "$tmpdir/kagenti_cli-${version}.dist-info/METADATA"
) > "$tmpdir/kagenti_cli-${version}.dist-info/METADATA.new"
mv "$tmpdir/kagenti_cli-${version}.dist-info/METADATA.new" "$tmpdir/kagenti_cli-${version}.dist-info/METADATA"
rm "$universal_wheel"
uv run -m wheel pack "$tmpdir" --dest-dir ./dist >/dev/null
rm -rf "$tmpdir"

# Verify that the wheel works
if ! uv tool run --isolated --from "$universal_wheel" --with ../adk-py/dist/kagenti_adk-*-py3-none-any.whl -- kagenti-adk version; then
  echo "Failed to install $universal_wheel"
  exit 1
fi

# Make platform-specific wheels by bundling limactl
build_wheel() {
  wheel_tag="$1"
  hostagent_arch="$2"
  tmpdir="$(mktemp -d)"
  
  # Unzip wheel and fix permissions
  unzip -q "$universal_wheel" -d "$tmpdir"
  find "$tmpdir" -type f -exec chmod +r {} \;

  # Add Lima binaries
  mkdir -p "$tmpdir/kagenti_cli/data/bin" "$tmpdir/kagenti_cli/data/share/lima"
  cp "./vendor/lima-$lima_version/$wheel_tag/bin/limactl" "$tmpdir/kagenti_cli/data/bin/"
  cp "./vendor/lima-$lima_version/$wheel_tag/share/lima/lima-guestagent.Linux-$hostagent_arch.gz" "$tmpdir/kagenti_cli/data/share/lima/"
  
  # Update WHEEL file
  perl -pi -e "s/Root-Is-Purelib: true/Root-Is-Purelib: false/" "$tmpdir/kagenti_cli-$version.dist-info/WHEEL"
  perl -pi -e "s/Tag: .*/Tag: py3-none-$wheel_tag/" "$tmpdir/kagenti_cli-$version.dist-info/WHEEL"

  uv run -m wheel pack "$tmpdir" --dest-dir ./dist >/dev/null
  rm -rf "$tmpdir"
}
build_wheel manylinux_2_34_x86_64  x86_64  &
build_wheel manylinux_2_34_aarch64 aarch64 &
build_wheel macosx_12_0_x86_64     x86_64  &
build_wheel macosx_12_0_arm64      aarch64 &
for job in $(jobs -p); do wait $job; done
'''

# docs

["adk-cli:docs"]
dir = "{{config_root}}/apps/adk-cli"
depends = ["adk-cli:setup"]
run = '''
#!/bin/bash
set -euo pipefail

CLI_REFERENCE="../../docs/development/reference/cli-reference.mdx"
TYPER_SCRIPT="src/kagenti_cli/__init__.py"

HEAD_TMP=$(mktemp)
GEN_TMP=$(mktemp)
trap 'rm -f $HEAD_TMP $GEN_TMP' EXIT

cat $CLI_REFERENCE | sed "/usage-generator/q" > $HEAD_TMP
uv run -m typer $TYPER_SCRIPT utils docs --name kagenti-adk | tail -n +2 > $GEN_TMP
cat $HEAD_TMP $GEN_TMP > $CLI_REFERENCE
'''
